#!/bin/bash

[ -z $PEARL_MAN_ROOT ] && PEARL_MAN_ROOT="$(dirname $(readlink -f "${BASH_ARGV[0]}"))"
if [ ! -d $PEARL_MAN_ROOT ]; then
    echo "Error: Could not set PEARL_MAN_ROOT env because $PEARL_MAN_ROOT does not exist."
    return 1
fi
[ -z $PEARL_HOME ] && PEARL_HOME=~/.config/pearl

mkdir -p ${PEARL_HOME}/markdown
mkdir -p ${PEARL_HOME}/mans/man/man1

function pearl_load_man(){
    local PEARL_MAN_MARKDOWN="${PEARL_HOME}/markdown"
    [ "$(ls -A $PEARL_MAN_MARKDOWN )" ] || return 0

    for md_file in ${PEARL_MAN_MARKDOWN}/*.markdown ${PEARL_MAN_MARKDOWN}/*.md
    do
        man_name=$(echo ${md_file} | sed -e 's/^.*\///g' \
            -e 's/\.1.markdown//' -e 's/\.markdown//' \
            -e 's/\.1.md//' -e 's/\.md//')
        man_file="${man_name}.1.gz"

        ${PEARL_MAN_ROOT}/mods/ronn/bin/ronn --roff --pipe --manual="${man_name}" \
            --organization="${USER}" "${md_file}" | \
            gzip -f -c > "${PEARL_HOME}/mans/man/man1/${man_file}"

        echo "Wrote ${man_file}"
    done
}

alias man3="pearl_load_man &> /dev/null; man -M ${PEARL_HOME}/mans/man:${PEARL_MAN_ROOT}/mans/man "

