.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HACKING" "1" "February 2014" "Filippo Squillace" "hacking"
.
.SH "keylogger with xinput"
To grab the output into a file: \fBscript \-c "xinput test ID" | cat /tmp/key\.log\fR
.
.P
To get the ID of the keyboard type: \fBxinput \-\-list\fR
