.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MYSQL" "1" "July 2014" "Filippo Squillace" "mysql"
.
.SH "common commands"
Access to mysql: \fBmysql \-u username \-\-protocol=tcp \-h hostname \-p\fR
.
.P
To show databases: \fBshow databases \eg\fR
.
.P
To use a database: \fBuse DATABASE \eg\fR
.
.P
To show tables in the current database: \fBshow tables \eg\fR
.
.P
To show the columne of a table: \fBshow columns from TABLE \eg\fR
.
.P
To show the description of a table: \fBdesc TABLE \eg\fR
.
.P
To query: \fBselect * from TABLE where FIELD like \'%something%\' \eg\fR
