.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NETWORK" "1" "July 2016" "Filippo Squillace" "network"
.
.SH "netcfg"
.
.IP "1." 4
Define a network in /etc/network\.d/ called mynetwork (copy one of the examples in the examples directory)
.
.IP "2." 4
Connection: \fBnetcfg mynetwork\fR
.
.IP "3." 4
Disconnection: \fBnetcfg down mynetwork\fR
.
.IP "4." 4
To Access at the menu any time (require dialog package): \fBnetcfg\-menu\fR
.
.IP "" 0
.
.SH "automatic connection"
You need to install the following package: * wpa_actiond \- for automatic/roaming wireless connection * ifplugd \- for automatic ethernet connection
.
.P
To connect profile during boot: 1\. Edit /etc/rc\.conf NETWORKS=(mynetwork yournetwork) DAEMONS=(\.\.\. net\-profiles \.\.\.)
.
.P
To connect to wireless networks with roaming support: 1\. Edit /etc/rc\.conf WIRELESS_INTERFACE="wlan0" DAEMONS=(\.\.\. net\-auto\-wireless \.\.\.)
.
.P
To connect to wired networks: 1\. edit /etc/rc\.conf WIRED_INTERFACE="eth0" DAEMONS=(\.\.\. net\-auto\-wired \.\.\.)
.
.SH "network"
Use /etc/rc\.conf to configure the network (interfaces, dhcp or static ip, gateway, etc\.\.\.) To restart the daemon: \fB/etc/rc\.d/network restart\fR
.
.SH "Create a daemon to change mac"
.
.IP "1." 4
Create a script set\-hw\-addr in /etc/rc\.d/
.
.IP "2." 4
In rc\.conf put it prior to network daemon: DAEMONS=(\.\.\. set\-hw\-addr network \.\.\.)
.
.IP "3." 4
Look at the source in https://wiki\.archlinux\.org/index\.php/Configuring_Network\-Change_MAC\.2Fhardware_address
.
.IP "" 0
.
.SH "tc"
Il comando tc serve alla configurazione del traffico in ingresso e uscita di una interfaccia di rete attraverso tecniche di shaping, scheduling, accodamento, etc\.\.
.
.P
Per rimuovere il qdisc esistente: \fBtc qdisc del dev $eth root\fR
.
.P
Per mostrare il qdisc esistente: \fBtc \-s qdisc show dev $eth\fR
.
.SH "ufw (Uncomplicated Firewall)"
Enable the firewall with the default rules defined in /etc/ufw/before6\.rules
.
.IP "" 4
.
.nf

ufw enable
.
.fi
.
.IP "" 0
.
.P
Allow traffic for ssh:
.
.IP "" 4
.
.nf

ufw allow ssh/tcp
.
.fi
.
.IP "" 0
.
.P
It is possible to see the effect of the operation via iptables:
.
.IP "" 4
.
.nf

iptables \-L \-vn
.
.fi
.
.IP "" 0
.
.SS "Logging and status"
Enable logging (visible with dmesg):
.
.IP "" 4
.
.nf

ufw logging on
.
.fi
.
.IP "" 0
.
.P
To check the status and remove the rule number 4:
.
.IP "" 4
.
.nf

ufw status numbered
ufw delete 4
.
.fi
.
.IP "" 0
.
.SS "Applications"
To list all the available apps:
.
.IP "" 4
.
.nf

ufw app list
.
.fi
.
.IP "" 0
.
.P
To get info about an app:
.
.IP "" 4
.
.nf

ufw app info Squid
.
.fi
.
.IP "" 0
.
.SS "Limit"
To limit access for ssh to a single IP for 6 simultaneous connections every 30 secs:
.
.IP "" 4
.
.nf

ufw limit ssh/cp
.
.fi
.
.IP "" 0
.
.SS "More examples"
To allow an ip to access to port 22 for all protocols:
.
.IP "" 4
.
.nf

ufw allow from 192\.168\.1\.10 to any port 22
.
.fi
.
.IP "" 0
.
.P
To allow a subnet to access to any app Samba:
.
.IP "" 4
.
.nf

ufw allow from 192\.168\.1\.0/24 to any app Samba
.
.fi
.
.IP "" 0
.
.SH "iptables"
General syntax: \fBiptables [\-t table] command [match] [target/jump]\fR
.
.SS "DISPLAY"
Display (\-L) numbered (\-\-line\-numbers) firewall rules without DNS resolution (\-n):
.
.P
\fBiptables \-n \-L \-v \-\-line\-numbers\fR
.
.SS "SET DEFAULT POLICY"
\fBiptables \-P INPUT DROP\fR
.
.SS "DELETE FIREWALL RULES"
Delete the rule numbered four (using \-\-line\-numbers to get the number):
.
.P
\fBiptables \-D INPUT 4\fR
.
.P
Delete from a particular rule:
.
.P
\fBiptables \-D INPUT \-s 202\.54\.1\.1 \-j DROP\fR
.
.P
Delete all rules: \fBiptables \-F\fR
.
.P
Delete a chain: \fBiptables \-X\fR
.
.P
Delete all rule for a table: \fBiptables \-t [nat|mangle] \-F\fR
.
.SS "INSERT OR APPEND FIREWALL RULES"
To insert in position 2: \fBiptables \-I INPUT 2 \-s 202\.54\.1\.2 \-j DROP\fR
.
.P
To append: \fBiptables \-A INPUT \-i eth1 \-s 192\.168\.0\.0/24 \-j DROP\fR
.
.SS "NAT"
Destination NAT: \fBiptables \-t nat \-A PREROUTING \-p tcp \-d 80\.182\.53\.192 \-dport 80 \-j DNAT \-to\-destination 10\.0\.0\.2:80\fR
.
.P
Source NAT: \fBiptables \-t nat \-A POSTROUTING \-o ppp0 \-j SNAT \-to\-source 150\.92\.48\.25\fR
.
.P
Redirect: \fBiptables \-t nat \-A PREROUTING \-p tcp \-\-destination\-port 80 \-j REDIRECT \-\-to\-port 10000\fR
.
.P
Masquerade (change the source IP with the public one): \fBiptables \-t nat \-A POSTROUTING \-o ppp0 \-j MASQUERADE\fR
.
.SS "SAVE/RESTORE"
Serve per salvare l\'insieme di regole (rule\-set) all\'interno di un file\. \-c serve a mantenere memorizzati i contatori dei byte e dei pacchetti\. Qst opzione può servire quando occorre chiudere il firewall, in qst modo le info relative alle quantità di byte e pacchetti rimangono comunque memorizzate\. \-t indica quali tabelle memorizzare (nat, mangle, filter, raw) nel file se omesso memorizza tutte le tabelle nel file\.
.
.P
\fBiptables\-save [\-c] [\-t table] > /etc/iptables/mytables\.rules\fR
.
.P
Serve a caricare il file fornito da iptables\-save nel kernel\. \-c serve a mantenere memorizzati i contatori dei byte e dei pacchetti\. Qst opzione può servire quando occorre chiudere il firewall, in qst modo le info relative alle quantità di byte e pacchetti rimangono comunque memorizzate\.\-n dice a iptables\-restore di non sovrascrivere le regole precedenti\. Di default le regole gia\' esistenti vengono eliminate\.
.
.P
\fBiptables\-restore [\-c] [\-n] < /etc/iptables/mytables\.rules\fR
.
.SS "VARIOUS EXAMPLES"
To block port 80 on IP range: \fBiptables \-A INPUT \-i eth1 \-p tcp \-s 192\.168\.1\.0/24 \-\-dport 80 \-j DROP\fR
.
.P
To block traffic for Facebook: Get the IP: \fBhost \-t a www\.facebook\.com\fR
.
.P
Get the belonging CIDR associated: \fBwhois 69\.171\.228\.40 | grep CIDR\fR
.
.P
Block all the outgoing traffic for that CIDR: \fBiptables \-A OUTPUT \-p tcp \-d 69\.171\.224\.0/19 \-j DROP\fR
.
.P
To Log packets in /var/log/messages: \fBiptables \-A INPUT \-i eth1 \-s 10\.0\.0\.0/8 \-j LOG \-\-log\-prefix "IP_SPOOF A: "\fR
.
.P
To log for 5 minutes with a limit of 5 entries: \fBiptables \-A INPUT \-i eth1 \-s 10\.0\.0\.0/8 \-m limit \-\-limit 5/m \-\-limit\-burst 7 \-j LOG \-\-log\-prefix "IP_SPOOF A: "\fR
.
.P
To drop packates from a MAC address: \fBiptables \-A INPUT \-m mac \-\-mac\-source 00:0F:EA:91:04:08 \-j DROP\fR
.
.P
To block a ping request: \fBiptables \-A INPUT \-p icmp \-\-icmp\-type echo\-request \-j DROP\fR
.
.P
Other icmp\-type are: * echo\-reply * destination\-unreachable * time\-exceeded
.
.P
To open a range of ports (supposing the default policy is DROP):
.
.P
\fBiptables \-A INPUT \-m state \-\-state NEW \-m tcp \-p tcp \-\-dport 7000:7010 \-j ACCEPT\fR
.
.P
To open for a range of IPs:
.
.P
\fBiptables \-A INPUT \-p tcp \-dport 80 \-m iprange \-\-src\-range 192\.168\.1\.100\-192\.168\.1\.200 \-j ACCEPT\fR
.
.P
To limit to 3 connections for the same host (\-\-syn is equivalent to \-\-tcp\-flags SYN,RST,ACK,FIN SYN):
.
.P
\fBiptables \-A INPUT \-p tcp \-dport 22 \-\-syn \-m connlimit \-\-connlimit\-above 3 \-j REJECT\fR
.
.SH "ipset"
Allow to keep the iptables rule simple by creating set of addresses or ports that be defined in entries of iptables\.
.
.SS "Set of ports"
To accept all incoming packets towards email ports (23, 110 and 143), we can create an \fIEmailPorts\fR set:
.
.IP "" 4
.
.nf

ipset create EmailPorts bitmap:port range 0\-65535 comment
ipset add EmailPorts 23 comment SMTP
ipset add EmailPorts 110 comment POP3
ipset add EmailPorts 143 comment IMAP
ipset add EmailPorts 152\-155 comment "Additional ports range"
.
.fi
.
.IP "" 0
.
.P
To list the sets:
.
.IP "" 4
.
.nf

ipset list
.
.fi
.
.IP "" 0
.
.P
To create the iptables rule:
.
.IP "" 4
.
.nf

iptables \-A INPUT \-s 192\.0\.2\.0/24 \-p tcp \-m set \-\-match\-set EmailPorts dst \-j ACCEPT
.
.fi
.
.IP "" 0
.
.SS "Set of hosts/subnet"
To accept packets from trusted hosts towards email ports:
.
.IP "" 4
.
.nf

ipset create TrustedHosts hash:ip family inet comment
ipset ad TrustedHosts 192\.0\.2\.10 comment "Alice"
ipset ad TrustedHosts 192\.0\.2\.15 comment "Bob"

iptables \-A INPUT \-p tcp \-\-dport 22 \-m set \-\-match\-set TrustedHosts src \-m set \-\-match\-set EmailPorts dst \-j ACCEPT
.
.fi
.
.IP "" 0
.
.P
To create a subnet:
.
.IP "" 4
.
.nf

ipset create NetworkList hash:net
ipset add NetworkList 10\.1\.0\.0/24
.
.fi
.
.IP "" 0
.
.SS "Combine hosts, protocols and ports"
.
.nf

ipset create AppSupport hash:ip,port
ipset add AppSupport 203\.0\.113\.15,tcp:5000
ipset add AppSupport 203\.0\.113\.15,tcp:5000
ipset add AppSupport 203\.0\.113\.15,tcp:5000

iptables \-A INPUT \-m set \-\-match\-set AppSupport src,dst \-j ACCEPT
.
.fi
.
.SS "Save and restore"
.
.nf

ipset save > /path/to/ipset\.save
ipset restore < /path/to/ipset\.save
.
.fi
.
.SH "nfs"
Server side: Pacchetti necessari:apt\-get install nfs\-kernel\-server nfs\-common portmap\. PASSI DA FARE: 1) scrivere in /etc/exports i permessi (es /home/ 192\.168\.210\.128/24(rw)) leggere il manuale (man exports)\. 2) Riavviare il server: /etc/init\.d/nfs\-kernel\-server restart oppure con exportfs \-a\. 3) Per verificare l\'esportazione showmount \-e Client side: Pacchetti necessari:apt\-get install portmap nfs\-common\. PASSI DA FARE: mount 192\.168\.210\.1:/home/ /mnt/HomeDiUbuntu 2) Se si vuole avviare al boot si modifica /etc/fstab cosi: 192\.168\.210\.1:/home/ /mnt/HomeDiUbuntu nfs rsize=8192,wsize=8192,timeo=14,intr
.
.SH "mtr"
Combine ping and traceroute in one tool giving info about packet loss: \fBmtr \-\-no\-dns 192\.168\.1\.1\fR
.
.P
To give a report: \fBmtr \-\-report 192\.168\.1\.1\fR
.
.SH "traceroute"
To track the route for a TCP connection in a particular port to a host: \fBtraceroute \-T \-p 3306 192\.168\.1\.1\fR
.
.P
To check if a TCP connection is working you can also use telnet: \fBtelnet 192\.168\.1\.1 3306\fR
.
.SH "tcptraceroute"
To track the route for a TCP connection in a particular port to a host: \fBtcptraceroute \-np 3306 192\.168\.1\.1\fR
.
.P
To check if a TCP connection is working you can also use telnet: \fBtelnet 192\.168\.1\.1 3306\fR
.
.SH "hping"
Modes are: * \-\-udp * \-\-tcp (default) * \-\-icmp * \-\-scan * \-\-listen * \-\-rawip
.
.P
Makes a traceroute: \fBsudo hping3 \-\-traceroute \-V \-\-udp www\.google\.com\fR
.
.P
Sends only one packet from port 6000 (\-S syn/\-A ack/\-F fin) on 80 port: \fBsudo hping3 \-c 1 \-V \-S \-p 80 \-s 6000 192\.168\.1\.1\fR
.
.P
Choose an arbitrary source IP and send packets to port 80 with interval 1500msec: \fBsudo hping3 \-\-spoof 1\.2\.3\.4 \-S 10\.20\.30\.40 \-p 80 \-i u1500\fR
.
.P
Also with random source IP: \fBsudo hping3 192\.168\.1\.1 \-\-udp \-\-rand\-source\fR
.
.P
Scan the port (using \-S syn/\-A ack/\-F fin): \fBsudo hping3 192\.168\.1\.1 \-S \-\-scan 1\-1024\fR
.
.SH "netcat"
The option \-p correspond always to the local port\. The option \-z is used for port scanning but not for sending data\.
.
.SS "Connect mode"
To check connection to server\.com:8080 from source port 1025 waiting for one second: \fBnc \-w1 \-z \-u \-p 1025 server\.com 8080\fR
.
.P
To send a message from client to server: \fBecho "nc is awesome!" | nc localhost 8080\fR
.
.SS "Listen mode"
To continuosly (with \-z) listen for UDP packets: \fBnc \-l \-p 8080 \-z localhost\fR
.
.P
To send a message from server to client: echo "Yeah, it is true!" | nc \-l \-p 8080
.
.SS "Execute remotely a command"
Listen to a port \- 3005 and execute /usr/bin/w command when client connects: \fB$ nc \-l \-p 3005 \-e /usr/bin/w\fR
.
.P
Later just do: \fBtelnet localhost 3005\fR
.
.SS "Check connectivity without netcat!"
.
.nf

exec 5<>/dev/tcp/time\.nist\.gov/13; cat <&5 & cat >&5; exec 5>&\-
.
.fi
.
.IP "\(bu" 4
exec sets up a redirect for /dev/tcp/$server/$host to file descriptor 5
.
.IP "\(bu" 4
first cat redirects from file descriptor 5 to STDOUT
.
.IP "\(bu" 4
second cat redirects STDIN to file descriptor 5
.
.IP "\(bu" 4
last exec cleans up the file descriptor
.
.IP "" 0
.
.P
Re: http://www\.commandlinefu\.com/commands/view/14406/read\-and\-write\-to\-tcp\-or\-udp\-sockets\-with\-common\-bash\-tools
.
.SH "socat"
Aka (SOcket CAT)\. It allows to establish two bidirectional byte streams that can be used for many purposes\.
.
.P
More info: http://www\.cyberciti\.biz/faq/linux\-unix\-tcp\-port\-forwarding/ Snippets: http://www\.dest\-unreach\.org/socat/doc/socat\.html#EXAMPLES
.
.SS "TCP proxy Port Forwarder"
To redirect all connections on port 80 to a remote host in port 22: \fBsudo socat TCP\-LISTEN:80,fork TCP:192\.168\.0\.2:22\fR
.
.P
Then you can access to the remote host via ssh using local connection: \fBssh \-p 80 localhost\fR
.
.SS "Listen mode"
Accept all connections in port 5555 and execute ls command in a sandbok with sandbox as user\. Use pty to communicate between socat and ls; redirect the stderr to stdout so that the error can be transferred via socat\. \fBsocat TCP4\-LISTEN:5555,fork \e EXEC:/bin/usr/ls,chroot=/home/sandbox,su\-d=sandbox,pty,stderr\fR
.
.P
Accept all connections and the data sent by the clients are appended to /tmp/in\.log\. Allow immediate restart of the server process (reuseaddr): \fBsocat \-u TCP4\-LISTEN:3334,reuseaddr,fork \e OPEN:/tmp/in\.log,creat,append\fR
.
.P
An OpenSSL server: \fBsocat SSL\-LISTEN:4443,reuseaddr,pf=ip4,fork,cert=server\.pem,cafile=client\.crt PIPE\fR
.
.SS "Connect to service"
Transfer data between stdin and local port 8080: \fBecho ciao | socat \- TCP4:localhost:8080\fR
.
.P
Transfer data with readline and store them in ~/\.http_history\. The option \-d \-d will print the progress and crnl will correct line termination char instead of NL: \fBsocat \-d \-d READLINE,history=$HOME/\.http_history TCP4:localhost:8080,crnl\fR
.
.P
Connect to ssh server\. Uses pty for communication between socat and ssh, control the ssh terminal tty (ctty) and makes the pty the owner of the new process group (setsid), so ssh accepts the password from socat: \fB(sleep 5; echo oneone; sleep 5; echo ls; sleep 1) | socat \- EXEC:\'ssh \-l feel 192\.168\.0\.23\',pty,setsid,ctty\fR
.
.P
A OpenSSL client that tries to connect to a SSL server\. In case of client authentication, the cert is used to specify the client certificate\. The first address (\'\-\') can be replaced by almost any other socat address: \fBsocat \- SSL:server:4443,cafile=server\.crt,cert=client\.pem\fR
.
.P
Unidirectional data transfer (\-u)\. Socat transfers data from file /tmp/readdata, starting at its current end (seek\-end=0 lets socat start reading at current end of file; use seek=0 or no seek option to first read the existing data) in a "tail \-f" like mode (ignoreeof)\. The "file" might also be a listening UNIX domain socket (do not use a seek option then): \fBsocat \-u /tmp/readdata,seek\-end=0,ignoreeof \-\fR
.
.SH "curl"
In generale, consente di trasferire documenti HTML request di tipo GET o POST e ricevere dal server response\. I parametri generali sono:
.
.P
\fB\-v\fR Estremamente utile per fare debug\. Mostra i messaggi che vengono trasferiti dal client al server e viceversa\.
.
.P
\fB\-i\fR Mostra i campi dell\'header nascosti
.
.P
\fB\-I\fR Mostra solo l\'header\.
.
.P
\fB\-X "type"\fR Definisci il tipo di request (GET, POST, PUT\.\.\.)
.
.P
\fB\-u "user":"pass"\fR Permette l\'autenticazione\. Nel caso in cui non funziona provare con queste altre opzioni \-\-ntlm, \-\-digest, \-\-negotiate o \-\-anyauth (in base alla risposta che da il server)
.
.P
\fB\-A "string"\fR Consente di cambiare il campo User\-Agent dell\'intestazione\. A volte conviene mettere user\-agent di un browser\.
.
.P
\fB\-L\fR Opzione molto utile\. Specifica a curl di seguire l\'url contenuto nel campo Location\.
.
.P
\fB\-H "string"\fR Personalizzazione dell\'header\. Ad esempio \-H "Destination: http://moo\.com/nowhere"
.
.P
\fB\-b "name=string/file"\fR Consente di leggere i cookies
.
.P
\fB\-c "file"\fR Scrive i cookies dopo l\'operazione
.
.P
\fB\-D "file"\fR Scrive gli header in questo file
.
.P
\fB\-d "string"\fR Corpo di una richiesta POST\. Conviene mandare i dati nello stesso ordine con cui un browser li manda\.
.
.P
\fB\-e "string"\fR Imposta un valore al campo Referer dell\'intestazione
.
.P
\fB\-G\fR Non molto utile\. Serve solo per specificare che i dati contenuti in \-d vengano usati per fare un HTTP GET piuttosto che un HTTP POST
.
.P
I campi di una form che sono nascosti (ad esempio input type=hidden) vengono gestiti allo stesso modo degli altri\. Gestisce automaticamente SSL\.
.
.P
HEAD Request (to get the info about the file and the server): \fBcurl \-I http://s0\.cyberciti\.org/images/misc/static/2012/11/ifdata\-welcome\-0\.png\fR
.
.P
GET Request: \fBcurl \-v \-c cookies\.txt \-b cookies\.txt \-L "www\.hotmail\.com/when/junk\.cgi?birthyear=1905&amp;press=OK"\fR
.
.P
POST Request: \fBcurl \-v \-c cookies\.txt \-b cookies\.txt \-L \-d "birthyear=1905&amp;press=%20OK%20" www\.hotmail\.com/when/junk\.cgi\fR dove l\'indirizzo url lo si trova nella form nell\'attributo action
.
.P
POST REquest with automatic data encode: \fBcurl \-c cookies\.txt \-b cookies\.txt \-L \-\-data\-urlencode "name=I am Daniel" www\.example\.com\fR
.
.P
PUT Request: \fBcurl \-v \-L \-c cookies\.txt \-b cookies\.txt \-T uploadfile www\.uploadhttp\.com/receive\.cgi\fR
.
.P
Quando nella form è presente l\'oggetto per uplodare file(ad esempio due oggetti nella form: input type=file name=upload e altro input type=submit name=press value=OK), esso può essere fatto tramite il seguente comando curl: \fBcurl \-v \-c cookies\.txt \-b cookies\.txt \-L \-F upload=@localfilename \-F press=OK [URL]\fR
.
.P
To know the public IP of your machine: \fBcurl ifconfig\.me\fR
.
.P
To know the public IP and other more info: \fBcurl http://freegeoip\.net/json/\fR
.
.P
To know the timezone: \fBcurl http://freegeoip\.net/tz/json/US/10\fR
.
.P
Resume a previous download partially completed: \fBcurl \-L \-O \-C \- http://ftp\.ussg\.iu\.edu/linux/centos/6\.5/isos/x86_64/CentOS\-6\.5\-x86_64\-bin\-DVD1\.iso\fR
.
.P
To download the first 20000 bytes and complete the remaining download later: \fBcurl \-o file\.png \-\-header "Range: bytes=0\-20000" http://s0\.cyberciti\.org/images/misc/static/2012/11/ifdata\-welcome\-0\.png\fR
.
.P
Or: \fBcurl \-r 0\-20000 \-o file\.png http://s0\.cyberciti\.org/images/misc/static/2012/11/ifdata\-welcome\-0\.png\fR
.
.P
\fBcurl \-o file\.png \-C 20001 http://s0\.cyberciti\.org/images/misc/static/2012/11/ifdata\-welcome\-0\.png\fR
.
.SS "Using Telnet"
Use the \'\-v\' option from curl you get the HTTP request can be used in \fItelnet\fR
.
.IP "" 4
.
.nf

telnet s0\.cyberciti\.org 80
GET /images/misc/static/2012/11/ifdata\-welcome\-0\.png HTTP/1\.1
Host: s0\.cyberciti\.org
Range: bytes=0\-1024
.
.fi
.
.IP "" 0
.
.SH "arp"
Consente di ricavare l\'indirizzo MAC a partire dall\'indirizzo IP: \fBarp 192\.168\.1\.1\fR
.
.SH "nmap"
Host discovery (ping scan): \fBnmap \-sP \-n 192\.168\.1\.0\-255\fR
.
.P
PORTS SCAN: Using SYN packets: \fBsudo nmap \-sS \-n 192\.168\.1\.\e*\fR
.
.P
Using ACK packets: \fBsudo nmap \-sA \-n \-A 192\.168\.1\.1\fR
.
.P
Using NULL: \fBsudo nmap \-sN \-n \-A 192\.168\.1\.1\fR
.
.P
Detect remote services version number(sV) and OS (A): \fBsudo nmap \-A \-sV 192\.168\.1\.1\fR
.
.P
When protected by firewall: \fBsudo nmap \-PN 192\.168\.1\.1\fR
.
.P
Scan specific port (with Tcp or Udp): \fBsudo nmap \-p U:53,111,137,T:21\-25,80,139,8080 192\.168\.1\.1\fR
.
.P
To read a list of host in a file and scan them: \fBsudo nmap \-iL /tmp/file\.txt\fR
.
.P
Show interface list and routes: \fBsudo nmap \-\-iflist\fR
.
.P
MAC spoof: \fBsudo nmap \-\-spoof\-mac MAC\-ADDRESS\-HERE 192\.168\.1\.1\fR
.
.P
Awesome GUI interface is zenmap
.
.SS "NSE (Nmap Security Engine) scripts"
.
.SH "macof"
consente di fare flooding su uno switch per facilitare lo sniffing!
.
.SH "lynx"
browser web su SHELL!!!!
.
.SH "ipcalc"
da info sull\'ind IP\. con \-h trova il nome dell\'host a partire dall\' IP
.
.SH "route"
permette di visualizzare/manipolare la tabella di routing di un interfaccia di rete\. \-n premette di visualizzare la tabella\. Es route add default gw 192\.168\.0\.1 permette di aggiungere un regola della tabella, route add \-host server\.it reject permette di rifiutare un indirizzo
.
.SH "etherape"
programma che visualizza il traffico di rete\. simile a wireshark
.
.SH "apachectl"
serve a start/stop apache
.
.SH "atftpd"
server FTP
.
.SH "slattach \-p cslip \-s 38400 ttyS1"
permette di creare un collegamento tra un interfaccia di rete e una linea seriale\. \-p "prot" indica il protocollo, \-s "speed" indica la velocità
.
.SH "vncserver"
permette di attivare VNCServer è necessario specificare la password per l\'accesso
.
.SH "minicom"
è una applicazione per la connessione telefonica ad un sistema, permettendo cosi di accedere ad un terminale del tipo ttyS0\. Basta semplicemente inserire il numero di telefono dell\'abitazione, username e password\. Per accedere come root ricordare di abilitare l\'accesso remoto sul terminale nel file /etc/securetty
.
.SH "ftp host port"
è un CLient FTP
.
.SH "ssh"
To access with enabling compression \fBssh \-C user@host\fR
.
.P
X11 Forwarding Per comprimere i dati trasmessi e abilitare l\'inoltro X11: \fBssh \-X \-C user@host\fR
.
.P
It\'s possible to use the option \-Y the X11 forward \fBssh \-Y \-C user@host\fR
.
.P
The X11 forward automatically set the DISPLAY variable environment in order to have the right forward\. So, it\'s not necessary to set the DISPLAY variable\. Se si vuole avviare un\'applicazione specificando un dato terminale: \fBexport DISPLAY=localhost:0\.0\fR
.
.P
Per mostrare i DISPLAY degli altri terminali attivi basta usare il comando who\.
.
.SS "ssh tunnelling (TCP forwarding)"
For define a ssh tunnel: \fBssh \-f \-N \-L localhost:24800:server:24800 user@server\fR
.
.P
Options:
.
.IP "\(bu" 4
\fB\-N\fR No remote command will be execute
.
.IP "\(bu" 4
\fB\-f\fR Set the ssh to background
.
.IP "\(bu" 4
\fB\-L\fR \fIport\fR define the local and remote socket which set the tunnel
.
.IP "" 0
.
.P
Additional options:
.
.IP "\(bu" 4
\fB\-p\fR \fIport\fR Port to connect to on the remote host
.
.IP "" 0
.
.P
In order to connect to a firewalled box (natbox) from an internet reachable box (openbox), establish a reverse tunnel in the natbox:
.
.P
\fBssh \-fN \-R 5555:localhost:22 openboxuser@OPENbox\.example\.com\fR
.
.P
This forward traffic on port 5555 of openbox to port 22 of natbox\.
.
.P
Options:
.
.IP "\(bu" 4
\fB\-R\fR \fIport\fR Specifies that the given port on the remote (server) host is to be forwarded to the given host and port on the local side\.
.
.IP "" 0
.
.P
Type the following command on OPENbox:
.
.P
\fBssh \-p5555 natboxuser@localhost\fR
.
.P
In order to reach the natbox endpoint from an external host outside the openbox host: \fBssh \-fN \-R OPENbox\.example\.com:5555:localhost:22 openboxuser@OPENbox\.example\.com\fR
.
.P
Then, you can access via from any host: \fBssh \-p5555 natboxuser@OPENbox\.example\.com\fR
.
.P
Ref\.: http://xmodulo\.com/access\-linux\-server\-behind\-nat\-reverse\-ssh\-tunnel\.html
.
.SS "Proxy command"
To go through one host to reach another server:
.
.IP "" 4
.
.nf

ssh \-t \-o ProxyCommand=\'ssh firewall_host nc remote_host 22\' remote_host
.
.fi
.
.IP "" 0
.
.P
Or:
.
.IP "" 4
.
.nf

ssh \-o "ProxyCommand ssh user@reachable_host \-W %h:%p" user@unreacheable_host
.
.fi
.
.IP "" 0
.
.P
Also:
.
.IP "" 4
.
.nf

ssh \-tt firewall_host ssh \-tt remote_host
.
.fi
.
.IP "" 0
.
.P
Ref\.: http://www\.cyberciti\.biz/faq/linux\-unix\-ssh\-proxycommand\-passing\-through\-one\-host\-gateway\-server/
.
.P
See also: \fIsocat\fR
.
.SH "telnet [\- l utente] [host [port]]"
telnet\. \-e [char] specifichi il carattere di escape per uscire dalla connessione
.
.SH "mail"
permette di spedire e ricevere posta da un utente ad un altro del sistema\. mail \-s "oggetto" \-u "utente" invia un msg all utente, \-f permette di visualizzare la casella di posta Send the output of a command: \fBecho test | mail \-s ASubject $USER@mail\.com\fR
.
.SH "talk utente@host opp talk pts/0"
permette di comunicare (non ho capito cm funziona)\. pts/0 specifica il terminale anziche l\'utente
.
.SH "write utente\-locale [tty]"
simile a talk ma unidirezionale, manda un messaggio ad un utente di un sistema\. tty indica il terminale su cui spedire il messaggio
.
.SH "mutt"
client di posta elettronica
.
.SH "irc [nick] server\.it"
chat\. /join \- canale permette di entrare in un canale, /leave \- canale permette di lasciarlo, /list \-MIN 5 \-MAX 20 \-PUBLIC \-NAME lista i canali con un min di partecipanti 5 e un max 20, di tipo publico e ordinati per nome, /help lista di comandi, /quit esci\. Esiste anche una chat migliore per console bitchx
.
.SH "netstat"
Shows all the connections active on the system\. Shows all connection UDP, TCP and Unix: \fBnetstat \-a\fR
.
.P
Only TCP/UDP connections: \fBnetstat \-aut\fR
.
.P
Doesn\'t make a DNS resolution (more efficient): \fBnetstat \-an\fR
.
.P
Shows the list Lista delle porte in ascolto: \fBnetstat \-l\fR
.
.P
Continue monitoring of connection: \fBnetstat \-c\fR
.
.P
Shows the processes with PID (use also lsof \-i): \fBnetstat \-pa\fR
.
.P
List of network interfaces: \fBnetstat \-i\fR
.
.P
Kernel routing table: \fBnestat \-r\fR
.
.P
Esiste un ulteriore comando denominato ss che consente di controllare i socket attivi sulla propria macchina
.
.SH "ipchains \-A input \-j REJECT \-s XXX\.XXX\.XXX\.XXX \-d 0/0 \-p all"
inibisce le connessione al sistema da parte XXX\.XXX\.XXX\.XXX, applicando una regola\.
.
.SH "Client per dhcp con dhclient"
Per richiedere al server dhcp un indirizzo IP invocare il seguente comando: \fBdhclient\fR
.
.SH "tcpdchk"
controlla la configurazione di TCP_WRAPPER segnalando config errate sui file /etc/hosts\.deny /etc/hosts\.allow
.
.SH "tcpdump"
Sniff packets from the interface eth0 and read the filtering rule from file: \fBtcpdump \-i eth0 \-F file\fR
.
.P
Display traffic from a particular host(\-p avoid promiscous mode of the interface): \fBtcpdump \-p \-nv host 192\.168\.1\.1\fR
.
.P
Display traffic about DNS: \fBtcpdump \-i eth1 \'udp port 53\'\fR
.
.P
Display all FTP session to 202\.54\.1\.5: \fBtcpdump \-i eth1 \'dst 202\.54\.1\.5 and (port 21 or 20)\'\fR
.
.P
Display all HTTP session to 192\.168\.1\.5: \fBtcpdump \-ni eth0 \'dst 192\.168\.1\.5 and tcp and port http\'\fR
.
.P
Use wireshark to view detailed information about files (\-s 0 allow to get all the bytes of the packages): \fBtcpdump \-n \-i eth1 \-s 0 \-w output\.txt src or dst port 80\fR
.
.P
To display all IPv4 HTTP packets to and from port 80, i\.e\. print only packets that contain data, not, for example, SYN and FIN packets and ACK\-only packets, enter:
.
.P
\fBtcpdump \'tcp port 80 and (((ip[2:2] \- ((ip[0]&amp;0xf)<<2)) \- ((tcp[12]&amp;0xf0)<<2)) != 0)\'\fR
.
.SH "ifconfig eth0 192\.168\.0\.1/24"
può configurare una interfaccia di rete in caso di assenza del dhcp per esempio\. 192\.168\.0\.1 è indIP, /24 indica la netmask
.
.SH "Deal with DNS lookup"
.
.SS "Static mapping"
In case the DNS does not contain the names required, a static mapping can be specified in \fB/etc/hosts\fR file\. For example the \fBlocalhost\fR name can be mapped to \fB127\.0\.0\.1\fR ip:
.
.IP "" 4
.
.nf

127\.0\.0\.1    localhost
.
.fi
.
.IP "" 0
.
.P
\fB\fIImportant NOTE\fR\fR:
.
.P
Make sure that the file \fB/etc/nsswitch\.conf\fR contains the line:
.
.IP "" 4
.
.nf

hosts:        files dns
.
.fi
.
.IP "" 0
.
.P
Which tells a program to first interrogate \fB/etc/hosts\fR file and then fall back to DNS\.
.
.P
There is \fB/etc/host\.conf\fR file that use a keyword \fIorder\fR which is used on old C library for controlling the order lookup\. Nowadays, \fB/etc/nsswitch\.conf\fR is the default file for domain name resolution\. The file \fB/etc/host\.conf\fR is still used for different purposes always related to the host lookup\.
.
.SS "Validate /etc/hosts mappings"
\fB\fIImportant NOTE\fR\fR:
.
.P
Do not use the commands \fBdig\fR or \fBhost\fR to validate the /etc/hosts file\. Those commands are for DNS purpose only and use \fIlibresolv\fR to perform DNS queries directly\.
.
.P
Fortunately, most applications use \fIgethostbyname\fR sys call that obeys to the config of \fB/etc/nsswitch\.conf\fR\. To perform a host lookup for testing \fB/etc/hosts\fR similarly to what an application would do use the following:
.
.IP "" 4
.
.nf

getent hosts serverfault\.com
.
.fi
.
.IP "" 0
.
.SS "/etc/resolv\.conf"
This file specify the DNS servers for hostname lookup\. For instance to add the Google DNS:
.
.IP "" 4
.
.nf

nameserver 8\.8\.8\.8
.
.fi
.
.IP "" 0
.
.P
Currently, you may include a maximum of three nameserver lines\.
.
.P
Since applications can override the content of the file \fB/etc/resolv\.conf\fR, you can create a file called /etc/resolv\.conf\.head containing your DNS servers that will get higher priority and no other applications are supposed to change it\.
.
.P
In order to refer to local hosts such as mainmachine1\.localdomain\.com as simply mainmachine1, add the following in \fB/etc/resolv\.conf\fR:
.
.IP "" 4
.
.nf

domain localdomain\.com
.
.fi
.
.IP "" 0
.
.SH "/etc/hosts\.{allow,deny}"
These files are kind of deprecated\. Alternative to them is to use tools such as iptables\.
.
.SS "/etc/hosts\.allow"
TCP_WRAPPERS Es\. sshd: 193\.207\.49\.111 host\.server\.org permette al sistema con ip 193\.207\.49\.111 di connettersi al proprio sistema utilizzando il demone sshd
.
.SS "/etc/hosts\.deny"
TCP_WRAPPERS Es\. \- Accesso vietato a chiunque, in quanto i servizi sono bloccati, basta aggiungere ALL:ALL@ALL, PARANOID
.
.SH "hostname"
Allow to temporarly change the hostname or get the current hostname of the machine\. To change permanently the hostname, change the content of the file located in \fB/etc/hostname\fR
.
.SH "gpg"
GESTIONE CHIAVI:
.
.P
Creare la directory di config in home in cui si inseriranno le chiavi: \fBgpg\fR
.
.P
Generare le chiavi: \fBgpg \-\-gen\-key\fR
.
.P
Esportare la kiave pubblica in formato ascii: \fBgpg \-\-export \-a \-o rsa\e_key\fR
.
.P
Importare una chiave per esempio di un altro utente: \fBgpg \-\-import new\e_key\fR
.
.P
Generare un certificato di revoca\. E\' consigliabile farlo non appena si genera una chiave e conservarlo in luogo sicuro: \fBgpg \-\-gen\-revoke\fR
.
.P
Lista chiavi del portachiavi: \fBgpg \-\-list\-keys\fR
.
.P
Lista firme: \fBgpg \-\-list\-sigs\fR
.
.P
Lista impronte digitali: \fBgpg \-\-fingerprint\fR
.
.P
Lista chiavi private: \fBgpg \-\-list\-secret\-keys\fR
.
.P
Cancellare una chiave pubblica: \fBgpg \-\-delete\-key UID\fR
.
.P
Cancellare una chiave privata: \fBgpg \-\-delete\-secret\-key UID\fR
.
.P
Modificare una chiave: \fBgpg \-\-edit\-key UID\fR
.
.P
Firma di un certificato serve a garantire l\'autenticità del certificato: Per firmare una chiave modificarla con \-\-edit\-key e eseguire il comando sign\.
.
.P
CIFRARE E DECIFRARE: Due opzioni possono essere usate per entrambe: \-u UID/\-\-local\-user UID per indicare la kiave privata\. \-r/\-\-recipient per modificare il destinatario\.
.
.P
Cifrare un testo in formato ascii: \fBgpg \-a \-e destinatario msg\.txt\fR
.
.P
Decifrare un testo in stdout(usare \-o file per stamparlo su file): \fBgpg \-d msg\.txt\.asc\fR
.
.P
To use a symmetric key to encrypt the document (and make it portable!): \fBgpg \-\-output doc\.asc \-\-symmetric doc\fR
.
.P
To decrypt the document with the symmetric encrypt: \fBgpg \-\-output doc \-\-decrypt doc\.asc\fR
.
.P
AUTENTICAZIONE (firmare e verificare le firme): Firmare testo: \fBgpg \-s (o \-\-sign) msg\.txt\fR
.
.P
Firmare senza fare compressione: \fBgpg \-\-clearsign msg\.txt\fR
.
.P
Firmare in un file separato (utile per file binari) puo\' essere utile anche l\'opzione \-\-armor: \fBgpg \-b (o \-\-detach\-sign) msg\.txt\fR
.
.P
Verifica di una firma (ovviamente e\' necessaria la chiave pubblica del mittente): \fBgpg \-\-verify msg\.txt\.asc\fR
.
.P
CIFRATURA E FIRMA: Cifrare e firmare nello stesso tempo: \fBgpg [\-u mittente] [\-r destinatario] [\-\-armor] \-\-sign \-e msg\.txt\fR
.
.P
NOTA: In ricezione, la firma deve essere verificata solo dopo aver decifrato il messaggio\.
.
.SH "\- grep Connect time\" /var/log/messages > | awk \'{min = $8} END {print min minuti di connessione\"}\'"
permette di conoscere il tempo di connessione
.
.SH "iwconfig"
analogo di ifconfig, serve a settare i parametri citati prima\.
.
.SH "iwlist"
fa uno scan per i peer o gli AP, o elenca le funzionalit? del driver
.
.SH "iwspy"
colleziona statistiche su un peer remoto della LAN
.
.SH "iwpriv"
parametri specifici del driver
.
.SH "iwevent"
monitor di eventi sull\'interfaccia
.
.SH "wlanconfig"
.
.SH "airodump\-ng"
sniffa pacchetti\. \-\-ivs specifica solo pacchetti ivs, \-w "file" scrive i pacchetti in un file, \-c "chan" indica il canale nel quale sniffare, \-bssid "AP" indica l\'AP in cui sniffare Sniffa i pacchetti contenti IV: \fBairodump\-ng \-c $chan \-w capturefile \-\-ivs ath1\fR
.
.SH "aircrack\-ng opts file_dump"
Programma per trovare la kiave: \fBaircrack\-ng \-a 1 \-e $AP \-b final\e_dump\.pcap\fR
.
.P
Serve per crakkare una kiave, \-e essid, \-b bssid, \-a algoritmo ad es\. 1 per WEP o 2 per WPA, \-n num si usa per specificare il num di bit della kiave se si conosce, \-f num es 3 o 4 piu\' e\' piccolo e piu\' il tempo diminuisce ma le possibilit? di trovare la kiave diminuiscono, \-w file serve per la WPA per un dizionario che puo\' essere scaricato opp generato da JohnTheRipper
.
.SH "ivstools \-\-merge <var>ivs file 1</var> <var>ivs file 2</var> \.\. <var>output file</var>"
Fonde in un singolo file tanti dump diversi
.
.SH "mergecap [options] \-w <var>outfile|\-</var> <var>infile</var> \.\.\."
simile a ivstools\. fa parte di wireshark\. es: mergecap \-T ieee\-802\-11 \-w final_dump\.pcap dump1\.pcap dump2\.pcap dump3\.pcap
.
.SH "airdecap\-ng"
decritta un pacchetto WEP/WPA data una chiave valida\.
.
.SH "kstats"
data una chiave valida, ed un dump, dice quale attacco statistico funziona meglio\.
.
.SH "makeivs"
genera un file pcap di test per provare il cracking con aircrack\-ng\.
.
.SH "packetforge\-ng"
Forgia un pacchetto in modo da poterlo usare con aireplay\-ng\. Genera un pacchetto da essere utilizzato con aireplay \-2 per iniettare pacchetti di tipo arp\-request nella rete, e fare l\'airodump:
.
.P
\fBpacketforge\-ng \-0 \-a $AP \-h $WIFI \-k 255\.255\.255\.255 \-l 255\.255\.255\.255 \-y ilFile\.xor \-w file\fR
.
.SH "airmon\-ng"
mette la scheda wireless in monitor mode\. es airmon\-ng start ath1
.
.SH "aireplay"
Inietta del traffico artificiale verso la rete\.
.
.P
Fake Authentication Serve per individuare se AP risponde come tempo mettere es 10 opp 0 sec\. Se AP non risponde, pu? darsi ci sia firewall MAC, in ogni caso non funzionera\' airodump:
.
.P
\fBaireplay\-ng \-e \- ssid rete\- \-a \- macAP\- \-h \- mioMAC\- \-\-fakeauth \- tempo\- \- nomescheda\-\fR
.
.P
Questo programma funziona similmente ad uno sniffer, andando alla ricerca dei pacchetti ARP request, ovvero i pacchetti interessanti al fine del crakkaggio\. Una volta ottenuto, inizia a rimandarlo all\'AP che risponder? con degli IV che verranno sniffati da airodump:
.
.P
\fBaireplay\-ng \-\-arpreplay \-b \- macAP\- \-h \-\- mioMAC\- \- nomescheda\-\fR
.
.P
Attacco di deautenticazione, Questo attacco puo\' essere usato per recuperare un SSID nascosto (cioe\' che non e\'broadcast), catturare una handshake WPA a 4 vie o lanciare un attacco di tipo Denial of Service\. Lo scopo dell\'attacco ? di obbligare il client a ri\-autenticarsi che, consente all\'aggressore di falsare gli indirizzi MAC:
.
.P
\fBaireplay\-ng \-0 $numVolte \-a $AP \-c $client ath0\fR
.
.P
Decriptare pacchetti WEP senza conoscere la chiave\. Vengono creati due file pcap: uno per il pacchetto decifrato e l\'altro per il relativo keystream\. il file \.cap puo\' essere letto da un lettore (es\. tcpdump); mentre il file \.xor puo\' essere utilizzato per falsare pacchetti e inviarli: \fBaireplay\-ng \-4 \-h $client ath0\fR
.
.P
Permette di ricavare il keystream con la tecnica del fragment: \fBaireplay\-ng \-5 \-b $AP \-h $WIFI ath1\fR
.
.P
Ritrasmissione di un pacchetto alterato con arpforge: \fBaireplay \-2 \-r forge\-arp\.cap ath0\fR
.
.P
tcpdump per leggere un plaintext ottenuto con aireplay\-ng \-4:
.
.P
\fBtcpdump \-s 0 \-n \-e \-r replay\e_dec\-0916\-114019\.cap\fR
.
.SH "arpforge replay_dec\-0916\-114019\.xor 1 $manDest $macSource $ipSource $ipDest forge\-arp\.cap"
Falsifica i pacchetti da un host all\'altro\. si puo recuperare il keystream con aireplay\-ng \-4
