.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SYSTEM\-MANAGEMENT" "1" "December 2015" "Filippo Squillace" "system-management"
.
.SH "Codici del comando exit"
Una volta eseguito un comando può essere controllato lo stato d\'uscita nel seguente modo: \fBecho $?\fR Questo ci consente di prendere successive decisioni in merito al uscita del comando eseguito\. In generale ogni codice ha un suo significato: * 1: general errors * 2: misuse of shell builtins (pretty rare) * 126: cannot invoke requested command * 127: command not found error * 128: invalid argument to “exit” * 128+n: fatal error signal “n” (for example, kill \-9 = 137)\. * 130: script terminated by Ctrl\-C
.
.SH "strace"
To check only some system call (i\.e\. open,\.\.) for a given process:
.
.P
\fBstrace \-f \-p pid \-e open,access,poll,select,connect,recvfrom,sendto [\-c]\fR
.
.SH "exec comando"
anziche generare un processo figlio per eseguire "comando", con exec la shell e\' sostituita dal comando\. Se exec viene utilizzato in uno script qst termina all\'esecuzione di exec
.
.SH "pidof"
Mostra il pid del processo passato come argomento: \fBpidof processo\fR
.
.SH "ulimit \-a"
mostra le limitazioni nelle risorse di sistema
.
.SH "top"
sorta di task manager in cui è possibile anche visualizzare la presenza di memoria swap\. in X Server esiste un app simile premendo i tasti CTRL+Esc
.
.SH "free"
To check RAM and swap state: \fBfree \-m\fR
.
.P
or sing meminfo: \fBwatch \-n 1 cat /proc/meminfo\fR
.
.P
To empty the caches: \fBsudo sysctl \-w vm\.drop_caches=3\fR
.
.SH "insmod"
"/lib/modules/2\.2\.17/sound/sound\.o" permette l\'inserimento di moduli per la gestione di periferiche e di funzionalità nella memoria\.Esiste la vecchia versione insmod\.old\. \-f forza l\'inserimento anche in caso di incompatibilità, \-k rende flessibile la gestione del modulo\.
.
.SH "lsmod /lib/modules/2\.2\.17/sound/sound\.o"
Visualizza i moduli caricati in memoria\. \-c visualizza le configurazioni, \-l lista, \-r rimuove moduli
.
.SH "modprobe"
carica moduli di memoria e li testa atraverso configurazioni\. con l\'opzione \-l lista la posizione dei vari moduli
.
.SH "modinfo modulo"
mostra informazioni sul modulo\.
.
.SH "rmmod"
rimuove un modulo in memoria\. \-a rimuove tutti i moduli
.
.SH "ps"
Lists of the processes in execution:
.
.IP "" 4
.
.nf

ps \-e
.
.fi
.
.IP "" 0
.
.P
Shows with more details:
.
.IP "" 4
.
.nf

ps aux
.
.fi
.
.IP "" 0
.
.P
Shows the process tree:
.
.IP "" 4
.
.nf

ps faxj
.
.fi
.
.IP "" 0
.
.P
OR
.
.IP "" 4
.
.nf

pstree
.
.fi
.
.IP "" 0
.
.P
Shows all processes for the getty command with customized fields:
.
.IP "" 4
.
.nf

ps \-C getty \-o user,pid,tty,time,comm
.
.fi
.
.IP "" 0
.
.P
Shows the first 10 processes sorted by CPU usage:
.
.IP "" 4
.
.nf

ps aux | sort \-n \-k 3 | tail \-10
.
.fi
.
.IP "" 0
.
.P
Shows the first 10 processes sorted by Memory usage:
.
.IP "" 4
.
.nf

ps aux | sort \-n \-k 4 | tail \-10
.
.fi
.
.IP "" 0
.
.P
Shows the processes running as a user:
.
.IP "" 4
.
.nf

ps \-U feel \-u feel u
.
.fi
.
.IP "" 0
.
.P
visualizza ulteriori info sui processi attivi\. si utilizzano le opzioni \-afx, \-a mostra i processi utilizzati da altri utenti, \-f definisce una struttura ad albero, \-x mostra processi senza terminali di controllo, u rende l\'output human\-readble
.
.P
See the pearl functions: touser, cpumost, memmost, topid, frompid
.
.SH "pstree"
Provide the list of process with a tree structure\. See also ps command\.
.
.SH "kill"
uccide il processo "pid" \fBkill pid\fR
.
.P
Elenco dei segnali che possono essere mandati al processo \fBkill \-l\fR
.
.P
I segnali più importanti sono: SIGHUP che consente di uccidere tutti i processi figli del processo specificato; SIGINT segnale di interruzione che corrisponde a Cntrl\-C; SIGKILL; SIGTSTP che corrisponde a Cntrl\-Z; SIGCONT che è il segnale inviato da una shell tramite i comandi fg e bg; SIGWINCH che è per eventi di finestra come resize e cosi via; e, infine SIGUSR1 e SIGUSR2 che permettono comunicazioni inter\-processo\.
.
.SH "batch \-f file\.sh"
esegue il file solo quando il carico della CPU scende (di 0\.8 per default)
.
.SH "time"
There two type of commands:
.
.IP "\(bu" 4
\fBtime\fR is a builtin shell command and provide the basic info on the execution time
.
.IP "\(bu" 4
\fB/usr/bin/time\fR is a command that determines the system resource usage during of execution of a particular command\.
.
.IP "" 0
.
.P
For getting extesive info:
.
.IP "" 4
.
.nf

/usr/bin/time \-v host
.
.fi
.
.IP "" 0
.
.SH "uptime"
stampa il tempo trascorso da quando il sistema e\' in funzione
.
.SH "nohup programma"
permette di eseguire un programma in background e rimanendo eseguito anche quando ci si disconnette dal sistema andando a riportare l\'output sul file nohup\.out nella dir corrente\. Vedere pure il comando \fBdisown\fR \.
.
.SH "Adjust process priorities"
The nice command assumes the value of 10\. The priority is a valuerange \-20 to 20\. The default priority is 0, priority 20 is the lowest possible\.
.
.P
To adjust the priority:
.
.IP "" 4
.
.nf

nice \-n num program
.
.fi
.
.IP "" 0
.
.SS "Alter priority on running processes"
To set the priority or the increment of a running process:
.
.IP "" 4
.
.nf

renice priority pid
renice \-n increment pid
.
.fi
.
.IP "" 0
.
.P
To set the processes belonging to a given user:
.
.IP "" 4
.
.nf

renice \-u user
.
.fi
.
.IP "" 0
.
.SH "watch \-n num comando"
Esegue un comando ripetutamente, ad intervalli di tempo specificati\.Gli intervalli preimpostati sono di due secondi, ma questo valore puo essere modificato mediante l\'opzione \-n\. es watch \-n 5 tail /var/log/messages
.
.SH "man [sezione] pagina"
La sezione e\' un numero\. visualizza i manuali dei comandi\. \-k "parola" cerca all\'interno dei manuali la parola (vedere il comando apropos che fa una operazione simile)\. e\' possibile fare una ricerca all\'interno del documento\. una volta entrati nel manuale digiare /"parola"
.
.SH "sudo comando"
esegue un comando come root\. il file /etc/sudoers contiene i nomi degli utenti autorizzatiad invocare sudo\. Il comando "sudo \-i" consente di utilizzare una console di root\. Per abilitare in ubuntu il root digitare "sudo passwd root"; per disabilitare nuovamente digitare "sudo passwd \-l root"\.
.
.SH "chroot root dir comando"
permette di eseguire un comando cambiando la directory di root\. Es\. chroot /mnt/backtrack /bin/bash esegue la bash sul SO linux presente ne filesystem backtrack!!! Addirittura!
.
.SH "ldd /usr/bin/comando"
permette di fornire info sulle librerie (sorte di \.dll) utilizzate dal comando
.
.SH "crontab"
esegue comandi ad una certa data\. è necessario che sia attivo il demone crond(attivabile con /etc/rc2\.d/S89cron start)\. \-e modifica il file di conf \-l lo visualizza \-r lo rimuove
.
.SH "at"
The general commands are: I comandi sono at, batch, atq, e atrm: * at esegue i comandi in un momento specificato\. * atq elenca i lavori in attesa dell’utente, a meno che l’utente non sia il superutente; in tal caso, tutti i lavori sono elencati\. * atrm elimina uno dei lavori in attesa, identificati dal loro numero\. * batch esegue comandi quando permesso dal livello di carico del sistema, in altre parole, quando il carico medio scende sotto 1\.5, o il valore specificato nella chiamata di atd
.
.P
To execute at script\.sh at 20\.00 send an email of the output and insert the job into the queue a: \fBat \-m \-q a \-f script\.sh 20\.00\fR
.
.P
Other possible values of time are "midnight Friday"
.
.P
To see the list of jobs: \fBatq\fR
.
.P
To see the detail of the job number 3: \fBat \-c 3\fR
.
.P
To remove the job number 3: \fBatrm 3\fR
.
.SH "init 0123456Ss"
permette di spostarsi sui vari runlevel
.
.SH "telinit 0123456\.\."
simile a init
.
.SH "runlevel"
visualizza il livello di runlevel corrente
.
.SH "/etc/inittab"
permette di modificare i processi che si avviano sui vari runlevel\. Ogni riga è del tipo id:run:azione:processo
.
.SH "/etc/rc\.d/rc\.local"
è letto da init in fase di avvio\. all\'interno si possono applicare i comandi che desideriamo avviare in fase di boot\. conviene disabilitare i comandi che generano issue e issue\.net che rappresentano banner informativi del proprio sistema\. di seguito conviene eventualmente eliminarli con il comando \- rm \-fr /etc/issue\.net /etc/issue
.
.SH "mesg opt"
permette di attivare(y) o disabilitare(n) la comunicazione tra utenti di sistema con l\'utilizzo di diversi programmi
.
.SH "sh file\.sh"
esegue degli script bash\. Usa sh \-c help per info su come costruire uno script shell\. è possibile eseguire un file\.sh anche in qst modo \./file\.sh\. in qst caso è necessario avere i permessi per farlo, che è possibile ottenere con chmod
.
.SH "whatis comando"
fornisce la descrizione di un comando\. è utile il comando makewhatis per creare l\'indice delle descrizioni\. il Comando apropos "parola" cerca all\'interno di elencho whatis, può essere una alternativa a whatis
.
.SH "whereis comando"
individua il percorso del comando binario, tra cui anche i file di configurazione, i manuali ecc\.\.\.
.
.SH "which comando"
restituisce il percorso di "comando" utile per capire se il comando e\' stato installato
