.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BITLBEE" "1" "July 2014" "Filippo Squillace" "bitlbee"
.
.SH "help"
General index: \fBhelp index\fR
.
.SH "first step"
To register your own account: \fBregister <password>\fR
.
.P
Add a gmail account: \fBaccount <account id> set username@gmail\.com password\fR
.
.P
Change password: \fBaccount <account id> set password <mypassword>\fR
.
.P
To see the setting related to this account: \fBacc gtalk set\fR
.
.P
Then set the "server","port" and "ssl" property accordingly\. Add a facebook account: \fBaccount add jabber user@chat\.facebook\.com\fR
.
.P
and enable it: \fBaccount fb set oauth on\fR
.
.SH "manage accounts and user"
List the accounts: \fBaccount list\fR
.
.P
To set server property: \fBaccount 0 set server talk\.google\.com\fR
.
.P
To set username: \fBaccount 0 set username foo@gmail\.com\fR
.
.P
To connect with an account: \fBaccount 0 on\fR
.
.P
To disconnect: \fBaccount gtalk off\fR
.
.P
To delete an account: \fBaccount 0 del\fR
.
.P
To see all the properties of an account: \fBaccount 0 set\fR
.
.P
To see all the properties of a user: \fBset\fR
.
.SH "chatting"
To add some contacts: \fBadd 0 r2d2@example\.com\fR
.
.P
To remove: \fBremove r2d2\fR
.
.P
To rename: \fBrename r2d3 r2d2\fR
.
.P
To chat in separate window: \fB/msg or /query\fR
.
.P
More features: To join in a new separate channel: \fB/join &amp;msn\fR
