.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BOOT" "1" "January 2015" "Filippo Squillace" "boot"
.
.SH "Boot kernel parameters"
Per conoscere tutte le opzioni al time boot:
.
.IP "" 4
.
.nf

man bootparam
.
.fi
.
.IP "" 0
.
.SH "Installare ubuntu senza cd ma solo con la iso"
Per prima cosa, scaricare l’immagine ISO di Ubuntu e posizionatela nella root directory (“/”), adesso digitate:
.
.P
\fBsudo gedit /boot/grub/grub\.cfg\fR
.
.P
A fine file aggiungete il seguente codice:
.
.P
menuentry "Ubuntu 10\.04 desktop" { loopback loop /ubuntu\-10\.04\-desktop\-i386\.iso linux (loop)/casper/vmlinuz boot=casper iso\-scan/filename=/ubuntu\-10\.04\-desktop\-i386\.iso noeject noprompt – initrd (loop)/casper/initrd\.lz }
.
.P
Adesso riavviate il sistema e troverete nel grub la voce “Ubuntu”, selezionatela e…\.partirà l’installazione di Ubuntu 10\.04 :)
.
.SH "Installare Grub nel MBR e in un\'altra partizione utilizzando chainloader"
Entrare in gurb con privilegi di root: \fBsudo grub\fR
.
.P
Per conoscere la partizione in cui è installato il proprio GRUB: \fBfind /boot/grub/stage1\fR
.
.P
Dal risultato ottenuto definire che quella partizione è la partizione principale \fBroot (hd0,0)\fR
.
.P
Installare il grub nel MBR: \fBsetup (hd0)\fR
.
.P
E per la partizione: \fBsetup (hd0,0)\fR
.
.SH "scrittura mbr"
1)si va in fdisk a cambiare il flag in modo tale che la partizione di linux sia bootable (\- fdisk /dev/sda; poi digita a; poi digita la partizione ) 2)si utilizza il CD live di ubuntu per esmpio cambiando le opzioni di boot (es root=/dev/sda2 eliminare il parametro boot=casper) 3)una volta avviato il SO scrivere su terminale sudo grub\-install /dev/sda
.
.P
In caso di errori del tipo error: no such disk quando si intende avviare XP provare con i seguenti comandi: \- update\-grub \- grub\-install /dev/sda
.
.SH "Grub 2"
To generate automatically the configuration from the files \fI/etc/default/grub\fR and the files located in \fI/etc/grub\.d/\fR:
.
.IP "" 4
.
.nf

grub\-mkconfig | grub\-script\-check
grub\-mkconfig \-o /boot/grub/grub\.cfg
.
.fi
.
.IP "" 0
.
.P
The main variable to set are:
.
.IP "" 4
.
.nf

GRUB_TIMEOUT \- elapsed time for the initial grub menu
GRUB_DISABLE_OS_PROBER \- disable the check of windows OS (grub may be faster by disabling this)
GRUB_CMDLINE_LINUX \- add the kernel extra options on all the entries
.
.fi
.
.IP "" 0

