.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "COREUTILS" "1" "August 2015" "Filippo Squillace" "coreutils"
.
.SH "NAME"
\fBcoreutils\fR
.
.SH "env/set"
To run a command to ignore the environment it inherits:
.
.IP "" 4
.
.nf

env \-i /usr/local/bin/wget www\.cyberciti\.biz
.
.fi
.
.IP "" 0

