.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CRYPT" "1" "April 2016" "Filippo Squillace" "crypt"
.
.SH "Password stored in Linux"
Hash passwords are stored in \fI/etc/shadow\fR file\. Each line contains the information separated by \fI:\fR:
.
.IP "\(bu" 4
Username
.
.IP "\(bu" 4
Hash password
.
.IP "\(bu" 4
Last password change in days since 1 Jan 1970
.
.IP "\(bu" 4
The minimum number of days required between password changes
.
.IP "\(bu" 4
The maximum number of days the password is valid
.
.IP "\(bu" 4
The number of days before password is to expire that user is warned
.
.IP "\(bu" 4
The number of days after password expires that account is disabled
.
.IP "\(bu" 4
Days since Jan 1, 1970 that account is disabled
.
.IP "" 0
.
.SS "Hash Password"
The Hash password is comprised of three different fields separated by \fI$\fR:
.
.IP "\(bu" 4
Chars representing cryptographic hashing mechanism used
.
.IP "" 0
.
.IP "" 4
.
.nf

  \- $1$  md5
  \- $2a$ Blowfish
  \- $2y$ Blowfish, with correct handling of 8 bit characters
  \- $5$  sha\-256
  \- $6$  sha\-512
.
.fi
.
.IP "" 0
.
.IP "\(bu" 4
A randomly generated salt
.
.IP "\(bu" 4
The hash resulting by combining the password, salt with the hashing mechanism
.
.IP "" 0
.
.P
To get the hash password from the plain one:
.
.TP
Using mkpasswd:
.
.IP
\fBmkpasswd \-\-method=sha\-512 \-\-salt=vb1tLY1qiY PASSWORD\fR
.
.TP
Using python:
.
.IP
\fBimport crypt\fR \fBcrypt\.crypt(\'PASSWORD\', \'$6$vb1tLY1qiY\')\fR
.
.TP
Using openssl (only for md5):
.
.IP
\fBopenssl passwd \-salt saltvalue \-1\fR

