.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DNS" "1" "August 2015" "Filippo Squillace" "dns"
.
.SH "overview"
The DNS lookup commands will allow to get answer to various dns queries such as: * the IP address (A) * mail exchanges (MX) * name servers (NS) * canonical name (cname) * text annotations (TXT) * ANY (all) type\.
.
.SH "host command"
To get IP address: \fBhost \-t a cyberciti\.biz\fR
.
.P
To find out the Domain Mail Server: \fBhost \-t mx cyberciti\.biz\fR
.
.P
To find Out the Domain Name Servers: \fBhost \-t ns cyberciti\.biz\fR
.
.P
To find Out the Domain SOA Record: \fBhost \-t soa cyberciti\.biz\fR
.
.P
To find Out the CNAME: \fBhost \-t cname cyberciti\.biz\fR
.
.P
To get all the Domain Records: \fBhost \-a cyberciti\.biz\fR
.
.P
To query Particular Name Server: \fBhost cyberciti\.biz ns2\.nixcraft\.net\fR
.
.P
Test your dns lookup using IPv6 query transport: \fBhost \-6 cyberciti\.biz\fR
.
.P
Reverse IP lookup: \fBhost 75\.126\.153\.206\fR
.
.P
Get TTL Information: \fBhost \-v \-t a cyberciti\.biz\fR
.
.SH "dig command"
IT is more powerful than host command\. Usage: \fBdig @ns\.example\.com example\.com TYPE\fR
.
.P
To trace for resolving the name: \fBdig +trace cyberciti\.biz\fR
.
.P
To get short answer: \fBdig +short cyberciti\.biz txt\fR
.
.P
To display all Domain Records: \fBdig +noall +answer cyberciti\.biz any\fR
.
.P
Reverse IP lookup: \fBdig \-x 75\.126\.153\.206 +short\fR
.
.P
To get the TTL: \fBdig +nocmd +noall +answer cyberciti\.biz a\fR
.
.P
A good command is: \fBdig +nocmd +noall +answer +ttlid aaaa www\.cyberciti\.biz\fR
.
.P
Few important options are: * +nocmd Toggles the printing of the initial comment in the output identifying the version of dig and the query options that have been applied\. This comment is printed by default\. * +noall Set or clear all display flags\. * +answer Display [do not display] the answer section of a reply\. The default is to display it\. * +ttlid Display [do not display] the TTL when printing the record\. * +short Display only the value of the query * +tcp Use TCP protocol instead of UDP
.
.P
To discover the real TTL from the authoritative server: \fBdig +trace +nocmd +noall +answer +ttlid aaaa www\.cyberciti\.biz\fR
.
.P
To get the public ip address: \fBdig +short myip\.opendns\.com @resolver1\.opendns\.com\fR
