.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EMACS" "1" "February 2014" "Filippo Squillace" "emacs"
.
.SH "Help"
Info\-browser: \fBC\-h i\fR
.
.P
General help: \fBCntrl\-h Cntrl\-h\fR
.
.P
Tutorial: \fBCntrl\-h t\fR
.
.P
Manual: \fBCntrl\-h r\fR
.
.P
Documentation with any key: \fBCntrl\-h k\fR
.
.P
Documentation for command by name: \fBCntrl\-h f\fR
.
.P
Search fo commands by keyword: \fBCntrl\-h a\fR
.
.SH "Files"
File chooser:
.
.P
\fBM\-x dired\fR or
.
.P
\fBC\-x C\-f\fR
.
.P
Save file: \fBC\-x C\-s\fR
.
.P
Save file as: \fBC\-x C\-w\fR
.
.SH "Misc"
To apply Cntrl\-c to the shell: \fBC\-q C\-c RET\fR
.
.P
To wrap line: \fBM\-q\fR
.
.SH "Movement"
Forward one char: \fBC\-f\fR
.
.P
Back one char: \fBC\-b\fR
.
.P
Next line: \fBC\-n\fR
.
.P
Previous line: \fBC\-p\fR
.
.P
Move one word: \fBC\-left or C\-right\fR
.
.P
Move one paragraph: \fBC\-up or C\-down\fR
.
.P
Beginning of line: \fBC\-a\fR
.
.P
End of line: \fBC\-e\fR
.
.P
Beginning of buffer: \fBM\-<\fR
.
.P
End of buffer: \fBM\->\fR
.
.P
Go to line: \fBC\-g g\fR
.
.P
Switch buffers: \fBC\-x b\fR
.
.P
List buffers: \fBC\-x C\-b\fR
.
.P
Move between buffers: \fBC\-x right or C\-x left\fR
.
.P
Kill buffer: \fBC\-x k\fR
.
.P
To recovery from a crash or to erase a keybindings sequence: \fBC\-g\fR
.
.SH "Search and replace"
Incermental search forward: \fBC\-s\fR
.
.P
Go to next: \fBC\-s\fR
.
.P
Return the cursor back: \fBC\-r\fR
.
.P
Incermental search backward: \fBC\-r\fR
.
.P
Search and Replace: \fBM\-%\fR
.
.P
REGULAR EXPRESSION: Apply a re: \fBC\-M\-s\fR
.
.P
Interactive: \fBM\-x re\-builder\fR
.
.P
List occurrences: \fBM\-x occur\fR
.
.P
Replace with re:
.
.P
\fBM\-x replace\-regexp\fR
.
.P
Then typing
.
.P
(\ew+) (\ew+) with \e,(upcase \e2), \e1
.
.P
Exchange the words and the second one become uppercased\.
.
.SH "Keyboard macro"
Start record: \fBF3\fR
.
.P
Stop record: \fBF4\fR
.
.P
Play macro: \fBF4\fR
.
.SH "Mark Yank kill undo"
Set Mark: \fBC\-SPC\fR
.
.P
Cut line: \fBC\-k\fR
.
.P
Cut region: \fBC\-w\fR
.
.P
Copy region: \fBM\-w\fR
.
.P
Paste line or region: \fBC\-y\fR
.
.P
Undo: \fBC\-x u\fR or \fBC\-_\fR
.
.SH "Programming"
Debugger: \fBM\-x gdb\fR
.
.P
Shell: \fBM\-x shell\fR
.
.P
For both shell and gdb use \fBM\-n\fR or \fBM\-p\fR to browse the history Terminal: \fBM\-x term\fR
.
.P
Shell Command: \fBM\-!\fR or
.
.P
\fBM\-x shell\-command\fR
.
.P
Man: \fBM\-x man\fR
.
.P
Grep: \fBM\-x grep\fR
.
.P
Calculator: \fBM\-x calculator\fR
.
.P
Calendar: \fBM\-x calendar\fR
.
.SH "Version Control"
Commit: \fBC\-x v v\fR
.
.P
Displays diff you have made: \fBC\-x v =\fR
.
.P
Prompts for a version number: \fBC\-x v ~\fR
.
.P
Displays for each line the relative commit:
.
.P
\fBC\-x v g\fR
.
.P
Then, press L to know the log message for that commit or press D to show the diff
.
.SH "Major minor modes"
List of major modes:
.
.P
\fBM\-x java\-mode\fR
.
.P
\fBM\-x python\-mode\fR
.
.P
\fBM\-x text\-mode\fR
.
.P
\fBM\-x fundamental\-mode\fR
.
.P
\fBM\-x org\-mode\fR
.
.P
\fBM\-x flyspell\-mode\fR
.
.P
List of minor modes:
.
.P
\fBM\-x auto\-fill\-mode\fR
.
.P
\fBM\-x flyspell\-mode\fR
.
.P
\fBM\-x follow\-mode\fR
.
.SH "Manage windows"
Leave the current window: \fBC\-x 1\fR
.
.P
Change window: \fBC\-x o\fR
.
.P
Create a window vertically: \fBC\-x 2\fR
.
.P
Create a window horizontally: \fBC\-x 3\fR
.
.P
Create a window and apply operation: \fBC\-x 4 \.\.\.\fR
.
.P
For example to send an email: \fBC\-x 4 m\fR
.
.P
Enlarge horizontally: \fBC\-x }\fR
.
.P
Shrink horizontally: \fBC\-x {\fR
.
.P
Enlarge vertically: \fBC\-x +\fR
.
.P
Shrink vertically: \fBC\-x \-\fR
.
.SH "Dired"
Open Dired: \fBC\-x d\fR
.
.P
Mark and Unmark: \fBm u\fR
.
.P
Flag deletion file: \fBd\fR
.
.P
Undo deletion file: \fBu\fR
.
.P
Delete the files: \fBx\fR
.
.P
Open on other window: \fBo\fR
.
.P
Rename file: \fBR\fR
.
.P
Copy file: \fBC\fR
.
.P
Delete file: \fBD\fR
.
.P
Change mode file: \fBM\fR
.
.P
Change owner file: \fBO\fR
.
.P
Change group file: \fBG\fR
.
.P
Touch file: \fBT\fR
.
.P
Compress file: \fBZ\fR
.
.P
Apply a shell command on a file: \fB!\fR
.
.P
Diff files: \fB=\fR
.
.P
Update Dired buffer: \fBg\fR
.
.SH "org\-mode"
Change priority: \fBS\-up or S\-down\fR
.
.P
Change state: \fBS\-left or S\-right\fR
.
.P
Move task: \fBM\-up or M\-down\fR
.
.P
Change outline level: \fBM\-left or M\-right\fR
.
.P
Add new line: \fBM\-RET\fR
.
.P
Cycle subtree: \fBTab\fR
.
.P
Global cycle: \fBS\-Tab\fR
.
.P
Markups are: \fIbold\fR /italic/ \fIunderline\fR +strike+ =code= ~verbatim~
.
.P
Create links: [[link]][[description]] To go to the link: \fBC\-c C\-o\fR
.
.P
To set the TODO types (place it at the beginning of the file and reload in the same line with C\-c C\-c):
.
.P
\fB\- +TODO: TODO IN\-PROGRESS WAITING DONE\fR
.
.P
CHECKBOXES: To add a checkobox to a list: \fB\- [ ]\fR
.
.P
To check the box: \fBC\-c C\-c\fR
.
.P
Add new checkbox: \fBM\-S\-RET\fR
.
.P
To get mandatory the check of the box in sequence:
.
.P
\fBC\-c C\-x o\fR
.
.P
TABLE: Just use the sequence: \fB|WORD\fR
.
.P
To set a separator: \fB|\- or C\-c \-\fR
.
.P
Convert a selection of CSV in table: \fBC\-c |\fR
.
.P
Move column/row around: \fBM\-(up/down/left/right)\fR
.
.P
Add/remove column/row: \fBM\-S\-(up/down/left/right)\fR
.
.P
New line: \fBC\-c RET\fR
.
.P
AGENDA: To open agenda command: \fBC\-c a\fR
.
.P
To set a time to an item: \fBC\-c \.\fR
.
.P
and then S\-left or S\-right to choose the day\. To add/remove a org file as agenda file: \fBC\-c [ or C\-c ]\fR
.
.P
CLOCKING: Clock in: \fBC\-c C\-x C\-i\fR
.
.P
Clock out: \fBC\-c C\-x C\-o\fR
.
.P
Reload a clock: \fBC\-c C\-c\fR
.
.P
Cancel clock: \fBC\-c C\-x C\-q\fR
.
.P
Displat a summary: \fBC\-c C\-x C\-d\fR
.
.P
Report table: \fBC\-c C\-x C\-r\fR
.
.P
DEADLINE and SCHEDULE: Create deadline: \fBC\-c C\-d\fR
.
.P
Create schedule: \fBC\-c C\-s\fR
.
.P
GTD (Get Things Done): To add a task to an item: \fBC\-c C\-q\fR
.
.P
To predefine some set of tags (at the beginning of the file):
.
.P
\fB\- +TAGS: { @OFFICE(o) @HOME(h) } COMPUTER(c) PHONE(p) READING(r)\fR
.
.P
EXPORT:
.
.P
\fBC\-x C\-e\fR
