.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PACMAN" "1" "February 2014" "Filippo Squillace" "pacman"
.
.SH "pacman"
To install package: \fBpacman \-S pack\fR
.
.P
Download a package without install it: \fBpacman \-Sw pack\fR
.
.P
To install a package from file: \fBpacman \-U file\.pkg\.tar\.xz or http://file\.pkg\.tar\.xz\fR
.
.P
To remove package: \fBpacman \-R pack\fR
.
.P
To remove package and its dipendencies: \fBpacman \-Rs pack\fR
.
.P
To remove package and its dipendencies and config files: \fBpacman \-Rns pack\fR
.
.P
To upgrade with the repository: \fBpacman \-Syu\fR
.
.P
If you don\'t want to upgrade a particular package: \fBpacman \-Syu \-\-ignore linux\fR
.
.P
To search in the database repository (both name and description): \fBpacman \-Ss string\fR
.
.P
to display extensive information: \fBpacman \-Si pack\fR
.
.P
To search in already installed package: \fBpacman \-Qs string\fR
.
.P
to display extensive information: \fBpacman \-Qi pack\fR
.
.P
to list all the files installed by a package: \fBpacman \-Ql pack\fR
.
.P
To know the list of packages explictly installed: \fBpacman \-Qeq\fR
.
.P
To know the whole list od packages installed: \fBpacman \-Qq\fR
.
.P
To know which package a file belongs to: \fBpacman \-Qo path/to/file\fR
.
.P
To list all the packages orphans: \fBpacman \-Qdt\fR
.
.P
To remove recursively all the orphans: \fBpacman \-Rs $(pacman \-Qtdq)\fR
.
.P
Clean the package cache (/var/cache/pacman/pkg/) of packages that are not currently installed\. Useful to do periodically: \fBpacman \-Sc\fR
.
.SH "makepkg"
To clean up the folder: \fBmakepkg \-c\fR
.
.P
To install needed dependencies automatically: \fBmakepkg \-s\fR
.
.SH "install package from aur"
Installing packages from the AUR (aka the [unsupported] repository) is a relatively simple process\. Essentially:
.
.IP "1." 4
Acquire the tarball which contains the PKGBUILD and possibly other required files
.
.IP "2." 4
Extract the tarball (preferably in a folder set aside just for builds from the AUR)
.
.IP "3." 4
Run makepkg in the directory where the files are saved ("makepkg \-s" will auto\-resolve dependencies with pacman)
.
.IP "4." 4
Install the resulting package with pacman \-U
.
.IP "" 0
.
.SH "local repository repo\-add repo\-remove"
.
.IP "1." 4
Create a directory of repository: \fBmkdir /home/feel/repo\fR
.
.IP "2." 4
Make a repository: \fBrepo\-add custom\.db\.tar\.gz *\.pkg\.tar\.gz\fR
.
.IP "3." 4
In file pacman\.conf put:
.
.IP "" 0
.
.P
[custom] Server = /home/feel/repo
.
.IP "1." 4
Upgrade: \fBpacman \-Syu\fR
.
.IP "" 0
.
.SH "Backing up and retrieving a list of installed packages"
Get the list of installed packages: \fBcomm \-23 <(pacman \-Qeq) <(pacman \-Qmq) > pkglist\fR
.
.P
Restore: \fBsudo pacman \-S $(< pkglist)\fR
.
.P
Look https://wiki\.archlinux\.org/index\.php/Pacman_Tips\- Custom_local_repository for more details\.
