.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SVN" "1" "February 2014" "Filippo Squillace" "svn"
.
.SH "NAME"
\fBsvn\fR \- subversion
.
.SH "svn \- semplice"
Le operazioni classiche compiute normalmente sono: Aggiornare la copia locale alla revisione più recente \fBsvn update\fR
.
.P
Commit della copia locale \fBsvn commit\fR
.
.P
Aggiungere file nella copia locale per aggiornare il contenuto della cartella \.svn \fBsvn add file\fR
.
.P
Rimuovere file nella copia locale per aggiornare il contenuto della cartella \.svn \fBsvn remove file\fR
.
.SH "svn \- avanzato"
Regredire ad una versione già “committed” \fBsvn merge \-c \-REV\fR dove REV è il numero di revisione che si intende recuperare\.
.
.P
Comprimere una directory escludendo i metadati SVN \fBtar cvf sdk\.tar \-\-exclude=\e\.svn sdk/\fR
.
.P
Eliminare gli spazi bianchi nel nome del file \fBsvn st | awk \'{if ($1 ~ "?") print $2}\' | xargs svn add\fR
.
.P
Rimuovere spazi o tabulazioni alla fine della riga \fBsed \'s/[ \et]*$//\' file1 > file2\fR
.
.P
Inviare SVN diff verso Meld \fBsvn diff \-\-diff\-cmd=\'meld\' \-r 100:BASE FILE\fR
.
.P
per visualizzare cosa è cambiato dalla versione “BASE” alla revisione “100″
.
.P
Quanti file ci sono nel repository SVN? \fBsvn log \-v \-\-xml file:///path/to/rep | grep kind=\e"file\e"|wc \-l\fR
.
.P
Accedere ad un repository SVN su una porta differente Editare il file di configurazione \fB/home/cicciobomba/\.subversion/config\fR e sotto la sezione [tunnels] aggiungere questa linea ciccio_diverso = /usr/bin/ssh \-p 12345 Adesso è possibile accedere al repository SVN tramite SSH sulla porta 12345 scrivendo \fBsudo svn co svn+ ciccio_diverso://root@192\.168\.50\.51/svn\-repo/progettino\fR
.
.P
Rimozione ricorsiva delle directory \.svn\. Questo comando l’ho sempre usato per eliminare i file “compilati” di Python \fBfind \. \-name "*\.pyc" \-exec rm \'{}\' \';\fR , ma può essere usato anche per eliminare le directory “\.svn” \fBfind \-name \.svn \-delete\fR
.
.P
Evitare le directory \.svn usando find \fBfind \. \-name \.svn \-prune \-o \-print\fR
