.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SYSTEMD" "1" "February 2014" "Filippo Squillace" "systemd"
.
.SH "system"
To boot the system: \fBsystemctl reboot\fR
.
.P
To poweroff the system: \fBsudo systemctl poweroff\fR
.
.P
Analyze the boot time in msec: \fBsystemd\-analyze\fR
.
.P
Ordered list of units sortex by init time: \fBsystemd\-analyze blame\fR
.
.P
Plot a graph of init time: \fBsystemd\-analyze plot\fR
.
.SH "system\-log"
BEST COMMAND: Show log from this boot for a specific unit:
.
.P
\fBjournatlctl \-xn \-b \-u UNITNAME\fR
.
.P
Follow new messages:
.
.P
\fBjournalctl \-f\fR
.
.P
BOOT: Shows messages from the current boot:
.
.P
\fBjournalctl \-b \-0\fR
.
.P
From the previous boot:
.
.P
\fBjournalctl \-b \-1\fR
.
.P
Show all messages by a specific process:
.
.P
\fBjournalctl _PID=1\fR
.
.P
Create a text file for the log: \fBjournalctl \-a > read_log\.txt\fR
.
.P
Get log a specific unit: \fBjournalctl _SYSTEMD_UNIT=systemd\-logind\.service\fR
.
.SH "services"
List of services: \fBsystemctl\fR
.
.P
List of active and non active services: \fBsystemctl list\-unit\-files\fR
.
.P
Start a service: \fBsystemctl start service\fR
.
.P
Stop a service: \fBsystemctl stop service\fR
.
.P
Restart a service: \fBsystemctl restart service\fR
.
.P
Reload a service: \fBsudo systemctl reload service\fR
.
.P
Show the status of a service: \fBsystemctl status service\fR
.
.P
Enable a service at boot: \fBsystemctl enable service\fR
.
.P
Disable a service at boot: \fBsystemctl disable service\fR
.
.P
Check whether a service is disabled: \fBsystemctl is\-enabled service; echo $?\fR
