.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "USER\-GROUP" "1" "January 2015" "Filippo Squillace" "user-group"
.
.SH "finger"
[\-sl][utente][@macchina]ottieni info su un utente o sulla macchina, quale e\' l\'ultima volta che è acceduto al sistema\. \-s forma breve, \-l forma estesa\.
.
.SH "adduser"
"utente"aggiunge un utente
.
.SH "groupadd gruppo"
aggiunge un gruppo
.
.SH "passwd"
serve a cambiare la password
.
.SH "sudo"
Da rivedere
.
.SH "su"
permette di cambiare utente
.
.SH "whoami"
.
.SH "who"
fornisce info sugli utenti connessi al sistema
.
.SH "last"
Show the last users that accessed into the system\. Ogni accesso viene di solito memorizzato su un file quando esiste /var/log/wtmp\. Con last si può visualizzare tale file\. n indica le righe da visualizzare\. con \-f indichiamo un altro file es /var/log/secure, \-d permette di conoscere in login remoti nn solo l\'utente ma il nome host e l\'IP associato, \-i è like \-d ma l\'IP è in forma 0\.0\.0\.0
.
.P
To show the last accesses of the user feel: \fBlast feel\fR
.
.SH "lslogins"
Show information about the user in the system
.
.SH "lastb"
gli accessi BAD vengono memorizzati in /var/log/btmp e visualizzati con tale comando\. Le opzioni sono le stesse del comando last
.
.SH "w \-f utente"
mostra gli utenti collegati al sistema e cosa stanno facendo\.\-f indica il terminale, IDLE indica il tempo in cui l\'utente non ha fatto nulla, JCPU e\' il tempo totale di CPU usato da quell\'utente, PCPU e\' il tempo totale di CPU usato per quel dato momento
