.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "XML\-URL" "1" "February 2014" "Filippo Squillace" "xml-url"
.
.SH "XML Encode"
\fB" \-> &quot;\fR
.
.P
\fB& \-> &amp;\fR
.
.P
\fB&apos; \-> &apos;\fR
.
.P
\fB< \-> &lt;\fR
.
.P
\fB> \-> &amp;gt;\fR
.
.P
More info: http://en\.wikipedia\.org/wiki/List_of_XML_and_HTML_character_entity_references Use CDATA construct to avoid code all special chars\.
.
.SH "URL Encode"
\fBTab \-> %09\fR
.
.P
\fBSpace \-> %20\fR
.
.P
\fB" \-> %22\fR
.
.P
\fB\- \-> %23\fR
.
.P
\fB% \-> %25\fR
.
.P
\fB&amp; \-> %26\fR
.
.P
\fB( \-> %28\fR
.
.P
\fB) \-> %29\fR
.
.P
\fB+ \-> %2B\fR
.
.P
\fB, \-> %2C\fR
.
.P
\fB\. \-> %2E\fR
.
.P
\fB/ \-> %2F\fR
.
.P
\fB: \-> %3A\fR
.
.P
\fB; \-> %3B\fR
.
.P
\fB< \-> %3C\fR
.
.P
\fB= \-> %3D\fR
.
.P
\fB> \-> %3E\fR
.
.P
\fB? \-> %3F\fR
.
.P
\fB@ \-> %40\fR
.
.P
\fB[ \-> %5B\fR
.
.P
\fB\e \-> %5C\fR
.
.P
\fB] \-> %5D\fR
.
.P
\fB^ \-> %5E\fR
.
.P
\fB\' \-> %60\fR
.
.P
\fB{ \-> %7B\fR
.
.P
\fB| \-> %7C\fR
.
.P
\fB} \-> %7D\fR
.
.P
\fB~ \-> %7E\fR
