.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README" "" "November 2016" "Filippo Squillace" "kobol"
.
.P
\fBTable of Contents\fR \- \fIDescription\fR \- \fIQuickstart\fR \- \fIInstallation\fR \- \fITroubleshooting\fR
.
.IP "\(bu" 4
name: \fBkobol\fR
.
.IP "\(bu" 4
description: \fBman\fR wrapper for reading user manuals from markdown files\.
.
.IP "\(bu" 4
author: Filippo Squillace
.
.IP "\(bu" 4
username: fsquillace
.
.IP "\(bu" 4
OS compatibility: linux, osx
.
.IP "" 0
.
.IP "\(bu" 4
Create the markdown file \fBmymanual\.md\fR in \fB$KOBOL_VARDIR/markdown\fR\.
.
.IP "\(bu" 4
To view the content of it as a manual (the manual will be generated just before viewing it):
.
.IP "" 0
.
.IP "" 4
.
.nf

$ kobol mymanual
.
.fi
.
.IP "" 0
.
.P
Every \fBman\fR options can be used in \fBkobol\fR as well\. For instance for searching according to the keyword \fIbanana\fR :
.
.IP "" 4
.
.nf

$ kobol \-K banana mymanual
.
.fi
.
.IP "" 0
.
.P
\fBkobol\fR creates the corresponding manual in \fB$KOBOL_VARDIR/mans\fR directory\.This package needs to be installed via Pearl \fIhttps://github\.com/pearl\-core/pearl\fR system\.
.
.IP "" 4
.
.nf

pearl install kobol
.
.fi
.
.IP "" 0
.
.P
\fBkobol\fR requires the ronn \fIhttps://github\.com/rtomayko/ronn\fR command to be installed:
.
.IP "" 4
.
.nf

gem install ronn
.
.fi
.
.IP "" 0
.
.SH "Dependencies"
The main dependencies are the following:
.
.IP "\(bu" 4
Pearl \fIhttps://github\.com/pearl\-core/pearl\fR
.
.IP "\(bu" 4
ronn \fIhttps://github\.com/rtomayko/ronn\fR
.
.IP "" 0
This section has been left blank intentionally\. It will be filled up as soon as troubles come in!
