.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README" "" "April 2016" "Filippo Squillace" "kobol"
.
.SH "Name"
kobol \- Snippet\-based manuals
.
.SH "Description"
kobol is a minimal system used to get essentials snippet information about all the important linux commands, programs, and much much more\. It contains the command \fBman3\fR that is a wrapper of the famous \fBman\fR\.
.
.P
The Pearl manuals are all located in \fB$PEARL_PKGDIR/mans/\fR\.
.
.P
You can create your own markdown manuals just place them to the directory \fB~/\.config/pearl/markdown\fR\.
.
.SH "Installation"
\fBkobol\fR is a \fIpearl\fR \fIhttps://github\.com/fsquillace/pearl\fR\.
.
.P
After installing pearl type just the following:
.
.IP "" 4
.
.nf

$ pearl install kobol
.
.fi
.
.IP "" 0
.
.SH "Usage"
.
.IP "\(bu" 4
To search for a "keyword" among all themans: \fBman3 \-K keyword\fR
.
.IP "\(bu" 4
To see a specific "manual": \fBman3 manual_name\fR
.
.IP "\(bu" 4
To create your own markdown document \fImydoc\fR, just save it in \fB~/\.config/pearl/markdown\fR and then:\fBman3 mydoc\fR
.
.IP "" 0
.
.SH "Help"
Just type one of the manuals you need in:
.
.IP "" 4
.
.nf

man pearl\.kobol
.
.fi
.
.IP "" 0
.
.SH "Copyright"
.
.nf

Copyright  (C) 2008\-2016 Free  Software Foundation, Inc\.

Permission  is  granted to make and distribute verbatim copies
of this document provided the copyright notice and  this  per‐
mission notice are preserved on all copies\.

Permission is granted to copy and distribute modified versions
of this document under the conditions  for  verbatim  copying,
provided that the entire resulting derived work is distributed
under the terms of a permission notice identical to this one\.

Permission is granted to copy and distribute  translations  of
this  document  into  another language, under the above condi‐
tions for  modified  versions,  except  that  this  permission
notice  may  be  stated  in a translation approved by the Free
Software Foundation\.
.
.fi
.
.SH "Bugs"
Of course there is no bug in pearl\. But there may be unexpected behaviors\. Go to \'https://github\.com/pearl\-hub/kobol/issues\' you can report directly this unexpected behaviors\.
.
.SH "Authors"
Filippo Squillace \fIfeel\.sqoox@gmail\.com\fR\.
.
.SH "WWW"
https://github\.com/fsquillace/pearl https://github\.com/pearl\-hub/kobol
.
.SH "Last words"
.
.nf

Consider your origins:
You were not born to live like brutes
but to follow virtue and knowledge\.
[verse, Dante Alighieri, from Divine Comedy]
.
.fi

